### ISSUE TITLE
Suspicious shared_ptr

### ISSUE THREAD

**Issue by versatran01** [KumarRobotics/imu_vn_100#1]
May be I'm wrong, but all those

```c++
pub_temp = nh.advertise<sensor_msgs::Temperature>("temperature", 1);
pub_temp_ptr = boost::shared_ptr<ros::Publisher>(&pub_temp);
```

look very suspicious/dangerous to me.

One workaround is to use a custom null deleter. Or maybe just use plain pointer?

**Comment by kartikmohta** [comment]
A plain pointer should be sufficient since it'll have the same scope as the object here.
