### ISSUE TITLE
ERROR: cannot launch node of type [imu_vn_100/imu_vn_100_cont_node]: Cannot locate node of type [imu_vn_100_cont_node] in package [imu_vn_100]. Make sure file exists in package path and permission is set to executable (chmod +x)

### ISSUE THREAD

**Issue by hilarioaraujo** [KumarRobotics/imu_vn_100#41]
Hello Sir, how are you?
I install your package and build them without any error.
When I was run the launch appear: ERROR: cannot launch node of type [imu_vn_100/imu_vn_100_cont_node]: Cannot locate node of type [imu_vn_100_cont_node] in package [imu_vn_100]. Make sure file exists in package path and permission is set to executable (chmod +x)

![Screenshot_20200403_022754](https://user-images.githubusercontent.com/47309365/78314740-c1f44280-7552-11ea-9275-28333becad59.png)

**Comment by lamlaaaam** [comment]
In the launch file change imu_vn_100_cont_node to imu_vn_100_node.

**Comment by fcladera** [comment]
Fixed by #43
