### ISSUE TITLE
Initialize Vector Processing Engine of VN-100

### ISSUE THREAD

**Issue by sagniknitr** [KumarRobotics/imu_vn_100#8]
I am unable to initialize the vpe of the vn-100 to get accurate ins data.

**Comment by ke-sun** [comment]
This functionality of vn-100 is currently not used by the library. But you are welcomed to extend the library. Some useful information may be found on p105-107 on the [user manual](http://www.vectornav.com/docs/default-source/documentation/vn-100-documentation/UM001.pdf?sfvrsn=12).
